# Generated by Django 6.0.3 on 2026-03-27 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_assessmentsession_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentsession',
            name='user',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='AssessmentSession',
        ),
    ]
