# Generated by Django 6.0.3 on 2026-03-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_alter_assignment_total_questions_assessmentsession'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsession',
            name='asked_questions',
            field=models.ManyToManyField(blank=True, to='questions.question'),
        ),
    ]
