# Generated by Django 6.0.3 on 2026-05-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_assessmentsession_asked_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsession',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
    ]
