# Generated by Django 6.0.3 on 2026-05-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_assessmentsession_total_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentsession',
            name='total_marks',
            field=models.IntegerField(default=30),
        ),
    ]
